import SwiftUI

// Every user-facing string of the report feature, in one file.
//
// Same rule and the same reason as `OnboardingCopy.swift`: `Shared/` is UI-free, and this is
// the copy bound by `.claude/skills/appstore_compliance/SKILL.md`. It matters more here than
// anywhere else in the app — this is the one surface a *third party* reads, so a claim that
// slips through is a claim made to somebody's doctor on the user's behalf.
//
// Two audiences, deliberately two voices:
//
//   - The screen speaks to the user, in the second person, like the rest of the app.
//   - The document speaks about them in the third person, because the person holding it is
//     not the person who made it.
//
// Mixing the two would have the PDF address a reader who never used the app.

// MARK: - Screen

/// Copy for the screen that builds the file.
enum ReportScreenCopy {

    /// The row in Settings.
    static var settingsRow: LocalizedStringKey { "Generate PDF report" }

    static var title: LocalizedStringKey { "Doctor report" }

    static var intro: LocalizedStringKey {
        "A summary of your pressure, your check-ins and what you took, as a PDF you can hand to a doctor."
    }

    static var periodHeader: LocalizedStringKey { "Period" }

    static var previewHeader: LocalizedStringKey { "Preview" }

    /// Under the preview card. The preview is the summary; the file is the summary plus the
    /// log, and a user who did not expect eight pages should find that out before sharing.
    static var previewNote: LocalizedStringKey {
        "The PDF also contains the full entry log for this period."
    }

    static var build: LocalizedStringKey { "Create PDF" }

    static var building: LocalizedStringKey { "Preparing…" }

    static var share: LocalizedStringKey { "Share" }

    /// Nothing is named as the cause because nothing here is actionable by the user, and the
    /// one thing worth saying is that no data went anywhere.
    static var failure: LocalizedStringKey {
        "Barosense could not build the file. Try again — nothing was sent anywhere."
    }

    static var emptyPeriod: LocalizedStringKey { "Nothing recorded in this period" }
}

extension ReportPeriod {

    /// Display text for the interval selector.
    var label: LocalizedStringKey {
        switch self {
        case .oneMonth: "1 month"
        case .threeMonths: "3 months"
        case .sixMonths: "6 months"
        case .twelveMonths: "12 months"
        }
    }
}

// MARK: - Document

/// Section headings and labels inside the generated document.
enum ReportDocumentCopy {

    static var title: LocalizedStringKey { "Wellbeing report" }

    /// Under the title, before the period line.
    static var subtitle: LocalizedStringKey { "Generated by Barosense from personal records" }

    // Sections, in the order the document prints them.
    static var aboutSection: LocalizedStringKey { "Who this report is about" }
    static var summarySection: LocalizedStringKey { "Summary" }
    static var traceSection: LocalizedStringKey { "Pressure and check-ins" }
    static var tagsSection: LocalizedStringKey { "Most-used tags" }
    static var medicationsSection: LocalizedStringKey { "Recorded medications" }
    static var sourcesSection: LocalizedStringKey { "Data sources" }
    static var entriesSection: LocalizedStringKey { "Entry log" }

    // Summary figures.
    static var checkInsFigure: LocalizedStringKey { "Check-ins" }
    static var daysFigure: LocalizedStringKey { "Days with entries" }
    static var dosesFigure: LocalizedStringKey { "Doses recorded" }

    /// The intensity line. Printed with its range attached, always: the scale is self-anchored
    /// and a bare "5.3" in a document someone else reads invites them to read it as a severity.
    static var intensityLabel: LocalizedStringKey { "Self-reported intensity, 1–10" }

    /// A function rather than a constant carrying `%@`, and so are the two below it.
    /// `LocalizedStringKey` derives its format specifiers from *interpolation* — a literal
    /// `%@` written into the key is matched against the catalogue verbatim and never filled
    /// in. `mean` arrives already formatted, so it is the caller that decides how a decimal
    /// is punctuated in the reader's language.
    static func intensityValues(mean: String, lowest: Int, highest: Int) -> LocalizedStringKey {
        "average \(mean) · lowest \(lowest) · highest \(highest)"
    }

    // Chart.
    static var pressureLegend: LocalizedStringKey { "Daily mean pressure, hPa" }
    static var checkInLegend: LocalizedStringKey { "Highest check-in that day, 1–10" }
    static var noPressure: LocalizedStringKey { "No barometer readings for this period" }

    // Tables.
    static var medicationColumn: LocalizedStringKey { "Medication" }
    static var doseColumn: LocalizedStringKey { "Dose" }
    static var timesColumn: LocalizedStringKey { "Times" }
    static var dateColumn: LocalizedStringKey { "Date" }
    static var intensityColumn: LocalizedStringKey { "1–10" }
    static var tagsColumn: LocalizedStringKey { "Tags" }
    static var takenColumn: LocalizedStringKey { "Taken" }

    /// Appended to a note the document had to cut. Says so rather than ending mid-sentence and
    /// letting a reader assume that is where the writer stopped.
    static var noteTruncated: LocalizedStringKey { "…shortened, full text is in the app" }

    static var entriesContinued: LocalizedStringKey { "Entry log (continued)" }
    static var medicationsContinued: LocalizedStringKey { "Recorded medications (continued)" }

    static var period: LocalizedStringKey { "Period" }
    static var generated: LocalizedStringKey { "Generated" }
    static var age: LocalizedStringKey { "Age" }

    static func ageValue(_ years: Int) -> LocalizedStringKey { "\(years) years" }

    static func footer(page: Int, of total: Int) -> LocalizedStringKey {
        "Barosense · created on device · page \(page) of \(total)"
    }

    static var nothingRecorded: LocalizedStringKey { "Nothing recorded in this period" }
}

extension ReportSource.Kind {

    /// What the "Data sources" block calls this line.
    var label: LocalizedStringKey {
        switch self {
        case .checkIns: "Check-in log"
        // Not "Recorded medications", which is the section heading above. Two keys that read
        // the same in English translate apart, and a catalogue with one shared entry for both
        // cannot express that.
        case .medications: "Medication entries"
        case .barometer: "Barometer readings"
        case .appleHealth: "Apple Health readings"
        }
    }
}

// MARK: - Disclaimer

/// The statement at the foot of every generated document.
///
/// Three paragraphs, each answering a different question a reader could reasonably have: what
/// this is, what the numbers in it are, and what they may now do with the file.
///
/// ## Why the forbidden words are in here
///
/// `.claude/skills/appstore_compliance/SKILL.md` bars "medical" and "diagnosis" from every
/// product surface, and the same checklist *requires* a plain-language statement that the app
/// is not medical advice. The two meet here: the rule exists to stop the app making a claim,
/// and these sentences are the negation of that claim. `scripts/ci/check-copy-vocabulary.sh`
/// exempts any line carrying "not medical", which is why each sentence that names one of those
/// words keeps it on the same physical line as that phrase. Do not re-wrap these literals
/// without re-reading that script.
enum ReportDisclaimerCopy {

    static var heading: LocalizedStringKey { "This report is not medical advice" }

    static var whatItIs: LocalizedStringKey {
        """
        Barosense built this report on the device, from entries a person made about \
        themselves. It sets out what they recorded, not measurements of their health. \
        It is not a diagnosis and not medical advice, and it does not replace talking to a doctor.
        """
    }

    static var whatTheNumbersAre: LocalizedStringKey {
        """
        The intensity figures are that person's own answers on a 1–10 scale that only they \
        anchor, so they cannot be compared with anyone else's. The pressure figures come from \
        the device barometer: they are pressure at the place of measurement, uncorrected for \
        altitude. Nothing here joins the two — they share one timeline so that a reader can \
        look for themselves, and Barosense asserts no connection between them.
        """
    }

    static var handling: LocalizedStringKey {
        """
        This file was created on the device. Barosense did not send it anywhere, and it leaves \
        the device only when the person shares it themselves. It holds data concerning health, \
        which European data protection law places in a special category (GDPR, Article 9). \
        Anyone holding a copy is responsible for it: keep it only as long as it is needed, \
        handle it as you would any health record, and do not pass it on without that person's \
        agreement.
        """
    }

    static var all: [LocalizedStringKey] { [whatItIs, whatTheNumbersAre, handling] }
}
